# frozen_string_literal: true

# Generated by hyrax:models:install
class Work < ActiveFedora::Base
  include ::Hyrax::WorkBehavior
  include ::Hyrax::BasicMetadata
  property :single_object, predicate: ::RDF::Vocab::DC.creator, multiple: false
  property :multiple_object, predicate: ::RDF::Vocab::DC.creator
end
