changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - major-ver
    - title: Exciting New Features 🎉
      labels:
        - minor-ver
    - title: Bug Fixes 🐞
      labels:
        - patch-ver
    - title: Database Changes
      labels:
        - database-changes
    - title: Other Changes
      labels:
        - "*"
