# Bixby coding conventions
# Added AllCops config for further modification
AllCops:
  TargetRubyVersion: 2.4
  DisabledByDefault: true
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    # Additions by Notch8
    - 'spec/test_app/**/*'
    - 'bin/*'

inherit_from: .rubocop_todo.yml

inherit_gem:
  bixby: bixby_default.yml

# Notch8 coding conventions
# @see https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
Metrics/BlockLength:
  Max: 495
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/test_app/db/schema.rb'

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

RSpec/ExampleLength:
  Max: 8
