# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

module Bulkrax
  RSpec.describe ExportersController, type: :controller do
    routes { Bulkrax::Engine.routes }

    let(:current_user) { FactoryBot.create(:user) }

    before do
      module Bulkrax::Auth
        def authenticate_user!
          @current_user = User.first
          true
        end

        def current_user
          @current_user
        end
      end
      described_class.prepend Bulkrax::Auth
      allow(controller).to receive(:authenticate_user!).and_return(true)
      allow(controller).to receive(:current_user).and_return(current_user)
    end

    # This should return the minimal set of attributes required to create a valid
    # Exporter. As you add validations to Exporter, be sure to
    # adjust the attributes here as well.
    let(:valid_attributes) do
      {
        name: 'Test Exporter',
        user_id: current_user.id,
        parser_klass: 'Bulkrax::CsvParser'
      }
    end

    let(:invalid_attributes) do
      {
        name: '',
        user_id: nil
      }
    end

    # This should return the minimal set of values that should be in the session
    # in order to pass any filters (e.g. authentication) defined in
    # ExportersController. Be sure to keep this updated too.
    let(:valid_session) { {} }

    describe 'GET #index' do
      it 'returns a success response' do
        Exporter.create! valid_attributes
        get :index, params: {}, session: valid_session
        expect(response).to be_successful
      end
    end

    describe 'GET #show' do
      it 'returns a success response' do
        exporter = Exporter.create! valid_attributes
        get :show, params: { id: exporter.to_param }, session: valid_session
        expect(response).to be_successful
      end
    end

    describe 'GET #new' do
      it 'returns a success response' do
        get :new, params: {}, session: valid_session
        expect(response).to be_successful
      end
    end

    describe 'GET #edit' do
      it 'returns a success response' do
        exporter = Exporter.create! valid_attributes
        get :edit, params: { id: exporter.to_param }, session: valid_session
        expect(response).to be_successful
      end
    end

    describe 'POST #create' do
      context 'with valid params' do
        it 'creates a new Exporter' do
          expect do
            post :create, params: { exporter: valid_attributes }, session: valid_session
          end.to change(Exporter, :count).by(1)
        end

        it 'redirects to the created exporter' do
          post :create, params: { exporter: valid_attributes }, session: valid_session
          expect(response).to redirect_to(exporters_path)
        end
      end

      context 'with invalid params' do
        it "returns a success response (i.e. to display the 'new' template)" do
          post :create, params: { exporter: invalid_attributes }, session: valid_session
          expect(response).to be_successful
        end
      end
    end

    describe 'PUT #update' do
      context 'with valid params' do
        let(:new_attributes) do
          {
            name: 'Test Exporter Updated',
            user_id: FactoryBot.create(:user).id
          }
        end

        it 'updates the requested exporter' do
          exporter = Exporter.create! valid_attributes
          put :update, params: { id: exporter.to_param, exporter: new_attributes }, session: valid_session
          exporter.reload
          expect(exporter.name).to eq('Test Exporter Updated')
        end

        it 'redirects to the exporter' do
          exporter = Exporter.create! valid_attributes
          put :update, params: { id: exporter.to_param, exporter: valid_attributes }, session: valid_session
          expect(response).to redirect_to(exporters_path)
        end
      end

      context 'with invalid params' do
        it "returns a success response (i.e. to display the 'edit' template)" do
          exporter = Exporter.create! valid_attributes
          put :update, params: { id: exporter.to_param, exporter: invalid_attributes }, session: valid_session
          expect(response).to be_successful
        end
      end
    end

    describe 'DELETE #destroy' do
      it 'destroys the requested exporter' do
        exporter = Exporter.create! valid_attributes
        expect do
          delete :destroy, params: { id: exporter.to_param }, session: valid_session
        end.to change(Exporter, :count).by(-1)
      end

      it 'redirects to the exporters list' do
        exporter = Exporter.create! valid_attributes
        delete :destroy, params: { id: exporter.to_param }, session: valid_session
        expect(response).to redirect_to(exporters_url)
      end
    end

    describe 'ownership enforcement' do
      let(:owner)      { FactoryBot.create(:user) }
      let(:other_user) { FactoryBot.create(:user) }
      let(:owned_exporter) do
        Exporter.create!(
          name: 'Owned Exporter',
          user_id: owner.id,
          parser_klass: 'Bulkrax::CsvParser'
        )
      end

      # Build a real CanCan ability that includes Bulkrax rules so that
      # load_and_authorize_resource can evaluate can? against the correct rules.
      def build_bulkrax_ability(user, admin: false)
        klass = Class.new do
          include CanCan::Ability
          include Bulkrax::Ability

          attr_reader :current_user

          def initialize(user, admin)
            @current_user = user
            @admin = admin
            bulkrax_default_abilities
          end

          def can_import_works?
            true
          end

          def can_export_works?
            true
          end

          def can_admin_importers?
            @admin
          end

          def can_admin_exporters?
            @admin
          end
        end
        klass.new(user, admin)
      end

      context 'when current user is not the owner and lacks admin ability' do
        before do
          allow(controller).to receive(:current_user).and_return(other_user)
          allow(controller).to receive(:current_ability)
            .and_return(build_bulkrax_ability(other_user))
        end

        it 'redirects (CanCan::AccessDenied rescued) for show' do
          get :show, params: { id: owned_exporter.to_param }, session: {}
          expect(response).to be_redirect
        end

        it 'redirects for edit' do
          get :edit, params: { id: owned_exporter.to_param }, session: {}
          expect(response).to be_redirect
        end

        it 'redirects for destroy' do
          delete :destroy, params: { id: owned_exporter.to_param }, session: {}
          expect(response).to be_redirect
        end
      end

      context 'when current user is the owner' do
        before do
          allow(controller).to receive(:current_user).and_return(owner)
          allow(controller).to receive(:current_ability)
            .and_return(build_bulkrax_ability(owner))
        end

        it 'allows show' do
          get :show, params: { id: owned_exporter.to_param }, session: {}
          expect(response).to be_successful
        end
      end

      context 'when current user has can_admin_exporters?' do
        before do
          allow(controller).to receive(:current_user).and_return(other_user)
          allow(controller).to receive(:current_ability)
            .and_return(build_bulkrax_ability(other_user, admin: true))
        end

        it 'allows show for any exporter' do
          get :show, params: { id: owned_exporter.to_param }, session: {}
          expect(response).to be_successful
        end
      end
    end
  end
end
