attributes:
  source_identifier:
    type: string
    multiple: false
    index_keys:
      - "source_identifier_sim"
      - "source_identifier_tesim"
    form:
      required: false
      primary: false
      multiple: false
